version: 0.2

phases:
    install:
        commands:
            - rm -f /etc/apt/sources.list.d/sbt.list #scala sbt bintray issue repo removal
            - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            - export NVM_DIR="$HOME/.nvm"
            - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
            - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'               
            - . "$NVM_DIR/nvm.sh" && nvm install lts/gallium
            - npm install path
            - npm install -g aws-cdk
            - npm install -g cdk8s-cli
            - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.9/bin/linux/amd64/kubectl
            - chmod +x ./kubectl
            - sudo mv ./kubectl /usr/local/bin/kubectl

    pre_build:
        commands:
            #- #echo $ANSIBLE_VAULT_PASSWORD >> ~/.vault-password
    build:
        commands:
            - git clone https://github.com/NachoAdasme/containerdeployer.git
            - cd containerdeployer
            #- ls -lta .
            - npm run compile
            - cdk8s synth
            - ls -lta ./dist
            - cat ./dist/*
            - aws eks --region us-west-2 update-kubeconfig --name k8s-dev-tf
            #- cat ~/.kube/config
            - kubectl apply -f ./dist/*.yaml
            - rm -rf /dist
            - rm -f ~/.kube/config

    post_build:
        commands:
            #- #|
               # sed -i 's/DOCKER_IDENTIFIER=//g' ../../playbooks/docker_identifier.txt
               # echo "The docker_identifier used to deploy was: $(cat ../../playbooks/docker_identifier.txt)"
artifacts:
    files:
        #- #playbooks/docker_identifier.txt
